name: sakurajima-infra

services:
  mongodb:
    image: mongo:7
    container_name: sakurajima-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ${SAKURAJIMA_DATA_DIR}/mongo:/data/db

  postgres:
    image: postgres:16
    container_name: sakurajima-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: sakurajima
      POSTGRES_PASSWORD: sakurajima
      POSTGRES_DB: sakurajima
    ports:
      - "5432:5432"
    volumes:
      - ${SAKURAJIMA_DATA_DIR}/postgres:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: sakurajima-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ${SAKURAJIMA_DATA_DIR}/redis:/data
